package coolabsensystem;

import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Harun Nurahman
 */
public class ManageMurid extends javax.swing.JDialog {
    Connection koneksi;
    String action, kls;
    public ManageMurid(java.awt.Frame parent, boolean modal, String act, String nis, String kelas) {
        super(parent, modal);
        initComponents();
        koneksi = CoolAbsenSystem.getKoneksi("localhost", "3306", "root", "", "absenkeren");
        action = act;
        kls = kelas;
        
        backPanel.setBackground(new Color(255, 255, 255));
        titlePanel.setBackground(new Color(229,13,58));
        
        tb_nis.setEnabled(false);
        comboShow();
        if (action.equals("edit")) {
            lblJudul.setText("Form Edit Siswa");
            showData(nis);
        } else {
            showTambahData();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backPanel = new javax.swing.JPanel();
        titlePanel = new javax.swing.JPanel();
        lblJudul = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tb_nis = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tb_nama = new javax.swing.JTextField();
        comKelas = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        lblJudul.setFont(new java.awt.Font("Tekton Pro", 0, 36)); // NOI18N
        lblJudul.setText("Form Tambah Siswa");

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titlePanelLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(lblJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel2.setText("NIS");

        tb_nis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_nisActionPerformed(evt);
            }
        });

        jLabel3.setText("Nama Siswa");

        tb_nama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tb_namaKeyPressed(evt);
            }
        });

        comKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comKelasActionPerformed(evt);
            }
        });
        comKelas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                comKelasKeyPressed(evt);
            }
        });

        jLabel5.setText("Kelas");

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backPanelLayout = new javax.swing.GroupLayout(backPanel);
        backPanel.setLayout(backPanelLayout);
        backPanelLayout.setHorizontalGroup(
            backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(backPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(backPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, backPanelLayout.createSequentialGroup()
                        .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tb_nis, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tb_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comKelas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        backPanelLayout.setVerticalGroup(
            backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backPanelLayout.createSequentialGroup()
                .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tb_nis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tb_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(backPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(comKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(btnSimpan)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        simpan();
    }//GEN-LAST:event_btnSimpanActionPerformed
    
    public void simpan(){
        String nis = tb_nis.getText();
        String nama = tb_nama.getText();
        String kelas = comKelas.getSelectedItem().toString();
        FormDataSiswaKeren rsa = new FormDataSiswaKeren();
        
        if(action.equals("edit")){
            try {
                Statement stmt = koneksi.createStatement();
                String query = "UPDATE t_murid SET nis = '"+nis+"',"
                        + "nm_siswa = '"+nama+"',"
                        + "kelas = '"+kelas+"' WHERE nis = '"+nis+"'";
                System.out.println(query);
                int berhasil = stmt.executeUpdate(query);
                if(berhasil == 1) {
                    JOptionPane.showMessageDialog(null, "Data Berhasil Diubah");
                } else {
                    JOptionPane.showMessageDialog(null, "Data Gagal Diubah");
                }           
            } catch (SQLException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null, "Terjadi Kesalahan Pada Query");
            }
        } else {
            try {
                Statement stmt = koneksi.createStatement();
                String query = "INSERT INTO t_murid (nis,nm_siswa,kelas)"
                        + "VALUES('"+nis+"','"+nama+"','"+kelas+"')";
                System.out.println(query);
                int berhasil = stmt.executeUpdate(query);
                if (berhasil == 1) {
                    for (int bln=1;bln<=12; bln++){
                        String quer = "INSERT INTO t_absen (nis, bulan)"
                            + "VALUES('"+nis+"', '"+bln+"')";
                        stmt.executeUpdate(quer);
                    }
                    JOptionPane.showMessageDialog(null, "Data Berhasil Dimasukkan");
                } else {
                    JOptionPane.showMessageDialog(null, "Data Gagal Dimasukkan");
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null, "Terjadi Kesalahan Pada Database");
            }
        }      
        
        rsa.showDataRPL();
        rsa.showDataTKJ();
        rsa.showDataMM();
        setVisible(false);
    }
    
    private void tb_nisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_nisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tb_nisActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        System.out.println(evt.getKeyCode());
    }//GEN-LAST:event_formKeyPressed

    private void tb_namaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tb_namaKeyPressed
        int key = evt.getKeyCode();
        if(key==10){
            simpan();
        }
    }//GEN-LAST:event_tb_namaKeyPressed

    private void comKelasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comKelasKeyPressed
        
    }//GEN-LAST:event_comKelasKeyPressed

    private void comKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comKelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comKelasActionPerformed

    
    public void comboShow(){
        try{
            Statement stmt = koneksi.createStatement();
            ResultSet rset = stmt.executeQuery("SELECT * FROM t_kelas");
            while(rset.next()){
                String s = rset.getString("kelas");
                comKelas.addItem(s);
            }
        } catch(SQLException ex){
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Terjadi Kesalahan di Query");
        }
    }
    
    void showTambahData(){
        try {
            Statement stmt = koneksi.createStatement();
            String query = "SELECT nis FROM t_murid ORDER BY nis DESC LIMIT 1 ";
            ResultSet rs = stmt.executeQuery(query);
            rs.first();
            int nomer = Integer.valueOf(rs.getString("nis"));
            nomer+=1;
            tb_nis.setText(String.valueOf(nomer));
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Terjadi Kesalahan di Query");
        }
    }
    
    void showData(String nis){
        try {
            Statement stmt = koneksi.createStatement();
            String query = "SELECT * FROM t_murid WHERE nis = '"+nis+"'";
            ResultSet rs = stmt.executeQuery(query);
            rs.first();
            tb_nis.setText(rs.getString("nis"));
            tb_nama.setText(rs.getString("nm_siswa"));
            comKelas.setSelectedItem(rs.getString("kelas"));
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Terjadi Kesalahan di Query");
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backPanel;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox comKelas;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JTextField tb_nama;
    private javax.swing.JTextField tb_nis;
    private javax.swing.JPanel titlePanel;
    // End of variables declaration//GEN-END:variables
}
